export const LOAD_STRINGS = 'LOAD_STRINGS';
export const LOAD_STRINGS_SUCCESS = 'LOAD_STRINGS_SUCCESS';
export const LOAD_STRINGS_FAIL = 'LOAD_STRINGS_FAIL';
export const UPDATE_STRINGS = 'UPDATE_STRINGS';
